Repository RaiseTech-team01/reservation_app, pull requests merged in 2021-08, with the labels that each got.

#150 [RAISETECH-80] 予約登録画面_時間帯
  rails_app/app/javascript/components/ReservationEdit.vue
  rails_app/app/javascript/components/ReservationForm.vue
  rails_app/app/javascript/components/dialog/FullCalendarDialog.vue
  rails_app/app/javascript/components/layout/ReservationInputs.vue
  rails_app/package.json
  rails_app/yarn.lock
Labels: reviewed

#177 [issue#171] 戻るボタンの不適切な挙動を修正
  rails_app/app/javascript/components/AccountInfo.vue
  rails_app/app/javascript/components/RegistrationConfirm.vue
  rails_app/app/javascript/components/RegistrationForm.vue
  rails_app/app/javascript/components/ReservationDetail.vue
  rails_app/app/javascript/components/ReservationList.vue
Labels: reviewed

#143 [RAISETECH-99] 管理_ダッシュボード画面
  rails_app/app/javascript/components/store/StoreDashBoard.vue
  rails_app/app/javascript/components/store/StoreLogin.vue
Labels: revieweing

#157 [RAISETECH-73] アカウント情報画面
  rails_app/app/javascript/components/AccountInfo.vue
  rails_app/app/javascript/utils/utils.js
Labels: revieweing

#192 [Issue#187] アカウント編集画面で編集した値をstateに反映させる
  rails_app/app/javascript/components/AccountEdit.vue
Labels: revieweing

#191 [Issue#186] アカウント入力画面表示時に最初の描画ではregistrationUserDataを利用しないように修正
  rails_app/app/javascript/components/RegistrationConfirm.vue
  rails_app/app/javascript/components/RegistrationForm.vue
  rails_app/app/javascript/components/layout/Navigation.vue
  rails_app/app/javascript/router/router.js
Labels: revieweing

#176 [issue#173] パンくずリストをコンポーネント化
  rails_app/app/javascript/components/AccountEdit.vue
  rails_app/app/javascript/components/AccountInfo.vue
  rails_app/app/javascript/components/Login.vue
  rails_app/app/javascript/components/RegistrationCompletion.vue
  rails_app/app/javascript/components/RegistrationConfirm.vue
  rails_app/app/javascript/components/RegistrationForm.vue
  rails_app/app/javascript/components/ReservationCompletion.vue
  rails_app/app/javascript/components/ReservationConfirm.vue
  rails_app/app/javascript/components/ReservationHistory.vue
  rails_app/app/javascript/components/ReservationList.vue
  rails_app/app/javascript/components/commons/layouts/BreadClumbList.vue
  rails_app/app/javascript/components/layout/ReservationInputs.vue
Labels: revieweing

#148 R74 予約一覧画面 & R75 予約詳細画面
  .editorconfig
  rails_app/app/javascript/components/ReservationDetail.vue
  rails_app/app/javascript/components/ReservationList.vue
  rails_app/app/javascript/components/layout/Header.vue
  rails_app/app/javascript/packs/hello_vue.js
  rails_app/app/javascript/store/getters.js
  rails_app/app/javascript/store/modules/userReservationData.js
  rails_app/app/javascript/store/modules/userReservationDetail.js
Labels: revieweing

#208 [Issue#207] フォーマットの適用（セミコロン除外）
  rails_app/app/javascript/components/AccountEdit.vue
  rails_app/app/javascript/components/AccountInfo.vue
  rails_app/app/javascript/components/Login.vue
  rails_app/app/javascript/components/RegistrationCompletion.vue
  rails_app/app/javascript/components/RegistrationConfirm.vue
  rails_app/app/javascript/components/RegistrationForm.vue
  rails_app/app/javascript/components/ReservationCompletion.vue
  rails_app/app/javascript/components/ReservationConfirm.vue
  rails_app/app/javascript/components/ReservationDetail.vue
  rails_app/app/javascript/components/ReservationEdit.vue
  rails_app/app/javascript/components/ReservationForm.vue
  rails_app/app/javascript/components/ReservationHistory.vue
  rails_app/app/javascript/components/ReservationList.vue
  rails_app/app/javascript/components/dialog/Calendar.vue
  rails_app/app/javascript/components/dialog/FullCalendarDialog.vue
  rails_app/app/javascript/components/dialog/Timetable.vue
  rails_app/app/javascript/components/layout/Header.vue
  rails_app/app/javascript/components/layout/Navigation.vue
  rails_app/app/javascript/components/layout/ReservationInputs.vue
  rails_app/app/javascript/components/layout/StoreHeader.vue
  rails_app/app/javascript/components/store/StoreAccountConfirm.vue
  rails_app/app/javascript/components/store/StoreAccountForm.vue
  rails_app/app/javascript/components/store/StoreDashBoard.vue
  rails_app/app/javascript/components/store/StoreLogin.vue
  rails_app/app/javascript/components/store/StoreReservationList.vue
  rails_app/app/javascript/components/store/StoreSettings.vue
  rails_app/app/javascript/components/store/StoreUserList.vue
  rails_app/app/javascript/packs/application.js
  rails_app/app/javascript/packs/hello_vue.js
  rails_app/app/javascript/router/router.js
  rails_app/app/javascript/store/getters.js
  rails_app/app/javascript/store/index.js
  rails_app/app/javascript/store/modules/auth.js
  rails_app/app/javascript/store/modules/registrationStoreUserData.js
  rails_app/app/javascript/store/modules/registrationUserData.js
  rails_app/app/javascript/store/modules/storeAuth.js
  rails_app/app/javascript/store/modules/storeUserData.js
  rails_app/app/javascript/store/modules/userData.js
  rails_app/app/javascript/store/modules/userReservationData.js
  rails_app/app/javascript/store/modules/userReservationDetail.js
  rails_app/app/javascript/utils/utils.js
  rails_app/app/packs/packs/application.js
  rails_app/babel.config.js
  rails_app/postcss.config.js
  rails_app/prettier.config.js
  rails_app/vetur.config.js
Labels: prettier
